name: "dartness"
version: "0.5.0"
description: "middleware based micro framework for dart. Made for rest api."
homepage: "https://github.com/0xff00ff/dartness"
dependencies:
  http_parser: "^4.0.1"
  mapper: "^0.2.3"
  cli_util: ^0.3.5
  mime: ^1.0.2
  logging: ^1.0.2
dev_dependencies:
  test: "^1.20.0"
environment:
  sdk: ">=2.12.0 <3.0.0"
executables:
  dartness: