name: "dartness"
version: "0.3.1"
author: "0xff00ff <0xff00ff@gmail.com>"
description: "middleware based micro framework for dart. Made for rest api."
homepage: "https://github.com/0xff00ff/dartness"
dependencies:
  body_parser: "^1.1.0"
  http_parser: "^3.0.0"
  mapper: "^0.2.0"
dev_dependencies:
  test: "^1.0.0"
environment:
  sdk: '>=2.0.0 <3.0.0'