name: "dartness"
version: "0.0.13"
author: "0xff00ff"
description: "micro framework for dart"
homepage: "https://github.com/0xff00ff/dartness"
dependencies:
  body_parser: "^1.1.0"
dev_dependencies:
  test: "^0.12.37"
